"""Added auth_id field.

Revision ID: 33291ac6c443
Revises: 38747306e5bd
Create Date: 2021-02-23 15:39:51.248072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33291ac6c443'
down_revision = '38747306e5bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('auth_id', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'user_model', ['auth_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_model', type_='unique')
    op.drop_column('user_model', 'auth_id')
    # ### end Alembic commands ###
